/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConsumerRouteImport } from './routes/_consumer'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ConsumerIndexRouteImport } from './routes/_consumer/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as ConsumerPurchasesIndexRouteImport } from './routes/_consumer/purchases/index'
import { Route as ConsumerCoursesIndexRouteImport } from './routes/_consumer/courses/index'
import { Route as ApiWebhooksPaymentRouteImport } from './routes/api/webhooks/payment'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminCoursesNewRouteImport } from './routes/admin/courses/new'
import { Route as ConsumerPurchasesPurchaseIdRouteImport } from './routes/_consumer/purchases/$purchaseId'
import { Route as ConsumerProductsPurchaseFailureRouteImport } from './routes/_consumer/products/purchase-failure'
import { Route as ConsumerProductsProductIdRouteImport } from './routes/_consumer/products/$productId'
import { Route as ConsumerCoursesCourseIdRouteImport } from './routes/_consumer/courses/$courseId'
import { Route as ApiPurchasesPaymentIdInvoiceRouteImport } from './routes/api/purchases/$paymentId.invoice'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products/$productId.edit'
import { Route as AdminCoursesCourseIdEditRouteImport } from './routes/admin/courses/$courseId.edit'
import { Route as ConsumerProductsProductIdPurchaseRouteImport } from './routes/_consumer/products/$productId.purchase'
import { Route as ConsumerProductsProductIdPurchaseSuccessRouteImport } from './routes/_consumer/products/$productId.purchase.success'
import { Route as ConsumerCoursesCourseIdLessonsLessonIdRouteImport } from './routes/_consumer/courses/$courseId.lessons.$lessonId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/_consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ConsumerIndexRoute = ConsumerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsumerRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const ConsumerPurchasesIndexRoute = ConsumerPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => ConsumerRoute,
} as any)
const ConsumerCoursesIndexRoute = ConsumerCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ConsumerRoute,
} as any)
const ApiWebhooksPaymentRoute = ApiWebhooksPaymentRouteImport.update({
  id: '/api/webhooks/payment',
  path: '/api/webhooks/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AdminRoute,
} as any)
const ConsumerPurchasesPurchaseIdRoute =
  ConsumerPurchasesPurchaseIdRouteImport.update({
    id: '/purchases/$purchaseId',
    path: '/purchases/$purchaseId',
    getParentRoute: () => ConsumerRoute,
  } as any)
const ConsumerProductsPurchaseFailureRoute =
  ConsumerProductsPurchaseFailureRouteImport.update({
    id: '/products/purchase-failure',
    path: '/products/purchase-failure',
    getParentRoute: () => ConsumerRoute,
  } as any)
const ConsumerProductsProductIdRoute =
  ConsumerProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => ConsumerRoute,
  } as any)
const ConsumerCoursesCourseIdRoute = ConsumerCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => ConsumerRoute,
} as any)
const ApiPurchasesPaymentIdInvoiceRoute =
  ApiPurchasesPaymentIdInvoiceRouteImport.update({
    id: '/api/purchases/$paymentId/invoice',
    path: '/api/purchases/$paymentId/invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCoursesCourseIdEditRoute =
  AdminCoursesCourseIdEditRouteImport.update({
    id: '/courses/$courseId/edit',
    path: '/courses/$courseId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const ConsumerProductsProductIdPurchaseRoute =
  ConsumerProductsProductIdPurchaseRouteImport.update({
    id: '/purchase',
    path: '/purchase',
    getParentRoute: () => ConsumerProductsProductIdRoute,
  } as any)
const ConsumerProductsProductIdPurchaseSuccessRoute =
  ConsumerProductsProductIdPurchaseSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => ConsumerProductsProductIdPurchaseRoute,
  } as any)
const ConsumerCoursesCourseIdLessonsLessonIdRoute =
  ConsumerCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => ConsumerCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsumerIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/sales': typeof AdminSalesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/$courseId': typeof ConsumerCoursesCourseIdRouteWithChildren
  '/products/$productId': typeof ConsumerProductsProductIdRouteWithChildren
  '/products/purchase-failure': typeof ConsumerProductsPurchaseFailureRoute
  '/purchases/$purchaseId': typeof ConsumerPurchasesPurchaseIdRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/courses/': typeof ConsumerCoursesIndexRoute
  '/purchases/': typeof ConsumerPurchasesIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/products/$productId/purchase': typeof ConsumerProductsProductIdPurchaseRouteWithChildren
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/api/purchases/$paymentId/invoice': typeof ApiPurchasesPaymentIdInvoiceRoute
  '/courses/$courseId/lessons/$lessonId': typeof ConsumerCoursesCourseIdLessonsLessonIdRoute
  '/products/$productId/purchase/success': typeof ConsumerProductsProductIdPurchaseSuccessRoute
}
export interface FileRoutesByTo {
  '/admin/sales': typeof AdminSalesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/': typeof ConsumerIndexRoute
  '/admin': typeof AdminIndexRoute
  '/courses/$courseId': typeof ConsumerCoursesCourseIdRouteWithChildren
  '/products/$productId': typeof ConsumerProductsProductIdRouteWithChildren
  '/products/purchase-failure': typeof ConsumerProductsPurchaseFailureRoute
  '/purchases/$purchaseId': typeof ConsumerPurchasesPurchaseIdRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/courses': typeof ConsumerCoursesIndexRoute
  '/purchases': typeof ConsumerPurchasesIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/products/$productId/purchase': typeof ConsumerProductsProductIdPurchaseRouteWithChildren
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/api/purchases/$paymentId/invoice': typeof ApiPurchasesPaymentIdInvoiceRoute
  '/courses/$courseId/lessons/$lessonId': typeof ConsumerCoursesCourseIdLessonsLessonIdRoute
  '/products/$productId/purchase/success': typeof ConsumerProductsProductIdPurchaseSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_consumer': typeof ConsumerRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/sales': typeof AdminSalesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_consumer/': typeof ConsumerIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_consumer/courses/$courseId': typeof ConsumerCoursesCourseIdRouteWithChildren
  '/_consumer/products/$productId': typeof ConsumerProductsProductIdRouteWithChildren
  '/_consumer/products/purchase-failure': typeof ConsumerProductsPurchaseFailureRoute
  '/_consumer/purchases/$purchaseId': typeof ConsumerPurchasesPurchaseIdRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/_consumer/courses/': typeof ConsumerCoursesIndexRoute
  '/_consumer/purchases/': typeof ConsumerPurchasesIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/_consumer/products/$productId/purchase': typeof ConsumerProductsProductIdPurchaseRouteWithChildren
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/api/purchases/$paymentId/invoice': typeof ApiPurchasesPaymentIdInvoiceRoute
  '/_consumer/courses/$courseId/lessons/$lessonId': typeof ConsumerCoursesCourseIdLessonsLessonIdRoute
  '/_consumer/products/$productId/purchase/success': typeof ConsumerProductsProductIdPurchaseSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/sales'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/courses/$courseId'
    | '/products/$productId'
    | '/products/purchase-failure'
    | '/purchases/$purchaseId'
    | '/admin/courses/new'
    | '/admin/products/new'
    | '/api/webhooks/clerk'
    | '/api/webhooks/payment'
    | '/courses/'
    | '/purchases/'
    | '/admin/courses/'
    | '/admin/products/'
    | '/products/$productId/purchase'
    | '/admin/courses/$courseId/edit'
    | '/admin/products/$productId/edit'
    | '/api/purchases/$paymentId/invoice'
    | '/courses/$courseId/lessons/$lessonId'
    | '/products/$productId/purchase/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/sales'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/'
    | '/admin'
    | '/courses/$courseId'
    | '/products/$productId'
    | '/products/purchase-failure'
    | '/purchases/$purchaseId'
    | '/admin/courses/new'
    | '/admin/products/new'
    | '/api/webhooks/clerk'
    | '/api/webhooks/payment'
    | '/courses'
    | '/purchases'
    | '/admin/courses'
    | '/admin/products'
    | '/products/$productId/purchase'
    | '/admin/courses/$courseId/edit'
    | '/admin/products/$productId/edit'
    | '/api/purchases/$paymentId/invoice'
    | '/courses/$courseId/lessons/$lessonId'
    | '/products/$productId/purchase/success'
  id:
    | '__root__'
    | '/_consumer'
    | '/admin'
    | '/admin/sales'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_consumer/'
    | '/admin/'
    | '/_consumer/courses/$courseId'
    | '/_consumer/products/$productId'
    | '/_consumer/products/purchase-failure'
    | '/_consumer/purchases/$purchaseId'
    | '/admin/courses/new'
    | '/admin/products/new'
    | '/api/webhooks/clerk'
    | '/api/webhooks/payment'
    | '/_consumer/courses/'
    | '/_consumer/purchases/'
    | '/admin/courses/'
    | '/admin/products/'
    | '/_consumer/products/$productId/purchase'
    | '/admin/courses/$courseId/edit'
    | '/admin/products/$productId/edit'
    | '/api/purchases/$paymentId/invoice'
    | '/_consumer/courses/$courseId/lessons/$lessonId'
    | '/_consumer/products/$productId/purchase/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsumerRoute: typeof ConsumerRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
  ApiWebhooksPaymentRoute: typeof ApiWebhooksPaymentRoute
  ApiPurchasesPaymentIdInvoiceRoute: typeof ApiPurchasesPaymentIdInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_consumer': {
      id: '/_consumer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_consumer/': {
      id: '/_consumer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsumerIndexRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_consumer/purchases/': {
      id: '/_consumer/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof ConsumerPurchasesIndexRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/_consumer/courses/': {
      id: '/_consumer/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof ConsumerCoursesIndexRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/api/webhooks/payment': {
      id: '/api/webhooks/payment'
      path: '/api/webhooks/payment'
      fullPath: '/api/webhooks/payment'
      preLoaderRoute: typeof ApiWebhooksPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_consumer/purchases/$purchaseId': {
      id: '/_consumer/purchases/$purchaseId'
      path: '/purchases/$purchaseId'
      fullPath: '/purchases/$purchaseId'
      preLoaderRoute: typeof ConsumerPurchasesPurchaseIdRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/_consumer/products/purchase-failure': {
      id: '/_consumer/products/purchase-failure'
      path: '/products/purchase-failure'
      fullPath: '/products/purchase-failure'
      preLoaderRoute: typeof ConsumerProductsPurchaseFailureRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/_consumer/products/$productId': {
      id: '/_consumer/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ConsumerProductsProductIdRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/_consumer/courses/$courseId': {
      id: '/_consumer/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof ConsumerCoursesCourseIdRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/api/purchases/$paymentId/invoice': {
      id: '/api/purchases/$paymentId/invoice'
      path: '/api/purchases/$paymentId/invoice'
      fullPath: '/api/purchases/$paymentId/invoice'
      preLoaderRoute: typeof ApiPurchasesPaymentIdInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId/edit': {
      id: '/admin/courses/$courseId/edit'
      path: '/courses/$courseId/edit'
      fullPath: '/admin/courses/$courseId/edit'
      preLoaderRoute: typeof AdminCoursesCourseIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_consumer/products/$productId/purchase': {
      id: '/_consumer/products/$productId/purchase'
      path: '/purchase'
      fullPath: '/products/$productId/purchase'
      preLoaderRoute: typeof ConsumerProductsProductIdPurchaseRouteImport
      parentRoute: typeof ConsumerProductsProductIdRoute
    }
    '/_consumer/products/$productId/purchase/success': {
      id: '/_consumer/products/$productId/purchase/success'
      path: '/success'
      fullPath: '/products/$productId/purchase/success'
      preLoaderRoute: typeof ConsumerProductsProductIdPurchaseSuccessRouteImport
      parentRoute: typeof ConsumerProductsProductIdPurchaseRoute
    }
    '/_consumer/courses/$courseId/lessons/$lessonId': {
      id: '/_consumer/courses/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof ConsumerCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof ConsumerCoursesCourseIdRoute
    }
  }
}

interface ConsumerCoursesCourseIdRouteChildren {
  ConsumerCoursesCourseIdLessonsLessonIdRoute: typeof ConsumerCoursesCourseIdLessonsLessonIdRoute
}

const ConsumerCoursesCourseIdRouteChildren: ConsumerCoursesCourseIdRouteChildren =
  {
    ConsumerCoursesCourseIdLessonsLessonIdRoute:
      ConsumerCoursesCourseIdLessonsLessonIdRoute,
  }

const ConsumerCoursesCourseIdRouteWithChildren =
  ConsumerCoursesCourseIdRoute._addFileChildren(
    ConsumerCoursesCourseIdRouteChildren,
  )

interface ConsumerProductsProductIdPurchaseRouteChildren {
  ConsumerProductsProductIdPurchaseSuccessRoute: typeof ConsumerProductsProductIdPurchaseSuccessRoute
}

const ConsumerProductsProductIdPurchaseRouteChildren: ConsumerProductsProductIdPurchaseRouteChildren =
  {
    ConsumerProductsProductIdPurchaseSuccessRoute:
      ConsumerProductsProductIdPurchaseSuccessRoute,
  }

const ConsumerProductsProductIdPurchaseRouteWithChildren =
  ConsumerProductsProductIdPurchaseRoute._addFileChildren(
    ConsumerProductsProductIdPurchaseRouteChildren,
  )

interface ConsumerProductsProductIdRouteChildren {
  ConsumerProductsProductIdPurchaseRoute: typeof ConsumerProductsProductIdPurchaseRouteWithChildren
}

const ConsumerProductsProductIdRouteChildren: ConsumerProductsProductIdRouteChildren =
  {
    ConsumerProductsProductIdPurchaseRoute:
      ConsumerProductsProductIdPurchaseRouteWithChildren,
  }

const ConsumerProductsProductIdRouteWithChildren =
  ConsumerProductsProductIdRoute._addFileChildren(
    ConsumerProductsProductIdRouteChildren,
  )

interface ConsumerRouteChildren {
  ConsumerIndexRoute: typeof ConsumerIndexRoute
  ConsumerCoursesCourseIdRoute: typeof ConsumerCoursesCourseIdRouteWithChildren
  ConsumerProductsProductIdRoute: typeof ConsumerProductsProductIdRouteWithChildren
  ConsumerProductsPurchaseFailureRoute: typeof ConsumerProductsPurchaseFailureRoute
  ConsumerPurchasesPurchaseIdRoute: typeof ConsumerPurchasesPurchaseIdRoute
  ConsumerCoursesIndexRoute: typeof ConsumerCoursesIndexRoute
  ConsumerPurchasesIndexRoute: typeof ConsumerPurchasesIndexRoute
}

const ConsumerRouteChildren: ConsumerRouteChildren = {
  ConsumerIndexRoute: ConsumerIndexRoute,
  ConsumerCoursesCourseIdRoute: ConsumerCoursesCourseIdRouteWithChildren,
  ConsumerProductsProductIdRoute: ConsumerProductsProductIdRouteWithChildren,
  ConsumerProductsPurchaseFailureRoute: ConsumerProductsPurchaseFailureRoute,
  ConsumerPurchasesPurchaseIdRoute: ConsumerPurchasesPurchaseIdRoute,
  ConsumerCoursesIndexRoute: ConsumerCoursesIndexRoute,
  ConsumerPurchasesIndexRoute: ConsumerPurchasesIndexRoute,
}

const ConsumerRouteWithChildren = ConsumerRoute._addFileChildren(
  ConsumerRouteChildren,
)

interface AdminRouteChildren {
  AdminSalesRoute: typeof AdminSalesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminCoursesCourseIdEditRoute: typeof AdminCoursesCourseIdEditRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSalesRoute: AdminSalesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminCoursesCourseIdEditRoute: AdminCoursesCourseIdEditRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsumerRoute: ConsumerRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
  ApiWebhooksPaymentRoute: ApiWebhooksPaymentRoute,
  ApiPurchasesPaymentIdInvoiceRoute: ApiPurchasesPaymentIdInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
