/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConsumerRouteImport } from './routes/_consumer'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ConsumerIndexRouteImport } from './routes/_consumer/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as ConsumerAuthedRouteImport } from './routes/_consumer/_authed'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as ApiWebhooksPaymentRouteImport } from './routes/api/webhooks/payment'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminCoursesNewRouteImport } from './routes/admin/courses/new'
import { Route as ConsumerPurchaseAfterRouteImport } from './routes/_consumer/purchase.after'
import { Route as ConsumerProductsProductIdRouteImport } from './routes/_consumer/products/$productId'
import { Route as ConsumerAuthedPurchasesIndexRouteImport } from './routes/_consumer/_authed/purchases/index'
import { Route as ConsumerAuthedCoursesIndexRouteImport } from './routes/_consumer/_authed/courses/index'
import { Route as ApiPurchasesPaymentIdInvoiceRouteImport } from './routes/api/purchases/$paymentId.invoice'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products/$productId.edit'
import { Route as AdminCoursesCourseIdEditRouteImport } from './routes/admin/courses/$courseId.edit'
import { Route as ConsumerProductsProductIdPurchaseRouteImport } from './routes/_consumer/products/$productId.purchase'
import { Route as ConsumerAuthedPurchasesPurchaseIdRouteImport } from './routes/_consumer/_authed/purchases/$purchaseId'
import { Route as ConsumerAuthedCoursesCourseIdSidebarRouteImport } from './routes/_consumer/_authed/courses/$courseId/_sidebar'
import { Route as ConsumerAuthedCoursesCourseIdSidebarIndexRouteImport } from './routes/_consumer/_authed/courses/$courseId/_sidebar/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/_consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ConsumerIndexRoute = ConsumerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsumerRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const ConsumerAuthedRoute = ConsumerAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => ConsumerRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhooksPaymentRoute = ApiWebhooksPaymentRouteImport.update({
  id: '/api/webhooks/payment',
  path: '/api/webhooks/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AdminRoute,
} as any)
const ConsumerPurchaseAfterRoute = ConsumerPurchaseAfterRouteImport.update({
  id: '/purchase/after',
  path: '/purchase/after',
  getParentRoute: () => ConsumerRoute,
} as any)
const ConsumerProductsProductIdRoute =
  ConsumerProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => ConsumerRoute,
  } as any)
const ConsumerAuthedPurchasesIndexRoute =
  ConsumerAuthedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => ConsumerAuthedRoute,
  } as any)
const ConsumerAuthedCoursesIndexRoute =
  ConsumerAuthedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => ConsumerAuthedRoute,
  } as any)
const ApiPurchasesPaymentIdInvoiceRoute =
  ApiPurchasesPaymentIdInvoiceRouteImport.update({
    id: '/api/purchases/$paymentId/invoice',
    path: '/api/purchases/$paymentId/invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCoursesCourseIdEditRoute =
  AdminCoursesCourseIdEditRouteImport.update({
    id: '/courses/$courseId/edit',
    path: '/courses/$courseId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const ConsumerProductsProductIdPurchaseRoute =
  ConsumerProductsProductIdPurchaseRouteImport.update({
    id: '/purchase',
    path: '/purchase',
    getParentRoute: () => ConsumerProductsProductIdRoute,
  } as any)
const ConsumerAuthedPurchasesPurchaseIdRoute =
  ConsumerAuthedPurchasesPurchaseIdRouteImport.update({
    id: '/purchases/$purchaseId',
    path: '/purchases/$purchaseId',
    getParentRoute: () => ConsumerAuthedRoute,
  } as any)
const ConsumerAuthedCoursesCourseIdSidebarRoute =
  ConsumerAuthedCoursesCourseIdSidebarRouteImport.update({
    id: '/courses/$courseId/_sidebar',
    path: '/courses/$courseId',
    getParentRoute: () => ConsumerAuthedRoute,
  } as any)
const ConsumerAuthedCoursesCourseIdSidebarIndexRoute =
  ConsumerAuthedCoursesCourseIdSidebarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConsumerAuthedCoursesCourseIdSidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsumerIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/sales': typeof AdminSalesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/products/$productId': typeof ConsumerProductsProductIdRouteWithChildren
  '/purchase/after': typeof ConsumerPurchaseAfterRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/purchases/$purchaseId': typeof ConsumerAuthedPurchasesPurchaseIdRoute
  '/products/$productId/purchase': typeof ConsumerProductsProductIdPurchaseRoute
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/api/purchases/$paymentId/invoice': typeof ApiPurchasesPaymentIdInvoiceRoute
  '/courses/': typeof ConsumerAuthedCoursesIndexRoute
  '/purchases/': typeof ConsumerAuthedPurchasesIndexRoute
  '/courses/$courseId': typeof ConsumerAuthedCoursesCourseIdSidebarRouteWithChildren
  '/courses/$courseId/': typeof ConsumerAuthedCoursesCourseIdSidebarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ConsumerIndexRoute
  '/admin/sales': typeof AdminSalesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin': typeof AdminIndexRoute
  '/products/$productId': typeof ConsumerProductsProductIdRouteWithChildren
  '/purchase/after': typeof ConsumerPurchaseAfterRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/purchases/$purchaseId': typeof ConsumerAuthedPurchasesPurchaseIdRoute
  '/products/$productId/purchase': typeof ConsumerProductsProductIdPurchaseRoute
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/api/purchases/$paymentId/invoice': typeof ApiPurchasesPaymentIdInvoiceRoute
  '/courses': typeof ConsumerAuthedCoursesIndexRoute
  '/purchases': typeof ConsumerAuthedPurchasesIndexRoute
  '/courses/$courseId': typeof ConsumerAuthedCoursesCourseIdSidebarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_consumer': typeof ConsumerRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_consumer/_authed': typeof ConsumerAuthedRouteWithChildren
  '/admin/sales': typeof AdminSalesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_consumer/': typeof ConsumerIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_consumer/products/$productId': typeof ConsumerProductsProductIdRouteWithChildren
  '/_consumer/purchase/after': typeof ConsumerPurchaseAfterRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/_consumer/_authed/purchases/$purchaseId': typeof ConsumerAuthedPurchasesPurchaseIdRoute
  '/_consumer/products/$productId/purchase': typeof ConsumerProductsProductIdPurchaseRoute
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/api/purchases/$paymentId/invoice': typeof ApiPurchasesPaymentIdInvoiceRoute
  '/_consumer/_authed/courses/': typeof ConsumerAuthedCoursesIndexRoute
  '/_consumer/_authed/purchases/': typeof ConsumerAuthedPurchasesIndexRoute
  '/_consumer/_authed/courses/$courseId/_sidebar': typeof ConsumerAuthedCoursesCourseIdSidebarRouteWithChildren
  '/_consumer/_authed/courses/$courseId/_sidebar/': typeof ConsumerAuthedCoursesCourseIdSidebarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/sales'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/products/$productId'
    | '/purchase/after'
    | '/admin/courses/new'
    | '/admin/products/new'
    | '/api/webhooks/clerk'
    | '/api/webhooks/payment'
    | '/admin/courses/'
    | '/admin/products/'
    | '/purchases/$purchaseId'
    | '/products/$productId/purchase'
    | '/admin/courses/$courseId/edit'
    | '/admin/products/$productId/edit'
    | '/api/purchases/$paymentId/invoice'
    | '/courses/'
    | '/purchases/'
    | '/courses/$courseId'
    | '/courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/sales'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin'
    | '/products/$productId'
    | '/purchase/after'
    | '/admin/courses/new'
    | '/admin/products/new'
    | '/api/webhooks/clerk'
    | '/api/webhooks/payment'
    | '/admin/courses'
    | '/admin/products'
    | '/purchases/$purchaseId'
    | '/products/$productId/purchase'
    | '/admin/courses/$courseId/edit'
    | '/admin/products/$productId/edit'
    | '/api/purchases/$paymentId/invoice'
    | '/courses'
    | '/purchases'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/_consumer'
    | '/admin'
    | '/_consumer/_authed'
    | '/admin/sales'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_consumer/'
    | '/admin/'
    | '/_consumer/products/$productId'
    | '/_consumer/purchase/after'
    | '/admin/courses/new'
    | '/admin/products/new'
    | '/api/webhooks/clerk'
    | '/api/webhooks/payment'
    | '/admin/courses/'
    | '/admin/products/'
    | '/_consumer/_authed/purchases/$purchaseId'
    | '/_consumer/products/$productId/purchase'
    | '/admin/courses/$courseId/edit'
    | '/admin/products/$productId/edit'
    | '/api/purchases/$paymentId/invoice'
    | '/_consumer/_authed/courses/'
    | '/_consumer/_authed/purchases/'
    | '/_consumer/_authed/courses/$courseId/_sidebar'
    | '/_consumer/_authed/courses/$courseId/_sidebar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsumerRoute: typeof ConsumerRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
  ApiWebhooksPaymentRoute: typeof ApiWebhooksPaymentRoute
  ApiPurchasesPaymentIdInvoiceRoute: typeof ApiPurchasesPaymentIdInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_consumer': {
      id: '/_consumer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_consumer/': {
      id: '/_consumer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsumerIndexRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_consumer/_authed': {
      id: '/_consumer/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsumerAuthedRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/payment': {
      id: '/api/webhooks/payment'
      path: '/api/webhooks/payment'
      fullPath: '/api/webhooks/payment'
      preLoaderRoute: typeof ApiWebhooksPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_consumer/purchase/after': {
      id: '/_consumer/purchase/after'
      path: '/purchase/after'
      fullPath: '/purchase/after'
      preLoaderRoute: typeof ConsumerPurchaseAfterRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/_consumer/products/$productId': {
      id: '/_consumer/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ConsumerProductsProductIdRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/_consumer/_authed/purchases/': {
      id: '/_consumer/_authed/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof ConsumerAuthedPurchasesIndexRouteImport
      parentRoute: typeof ConsumerAuthedRoute
    }
    '/_consumer/_authed/courses/': {
      id: '/_consumer/_authed/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof ConsumerAuthedCoursesIndexRouteImport
      parentRoute: typeof ConsumerAuthedRoute
    }
    '/api/purchases/$paymentId/invoice': {
      id: '/api/purchases/$paymentId/invoice'
      path: '/api/purchases/$paymentId/invoice'
      fullPath: '/api/purchases/$paymentId/invoice'
      preLoaderRoute: typeof ApiPurchasesPaymentIdInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId/edit': {
      id: '/admin/courses/$courseId/edit'
      path: '/courses/$courseId/edit'
      fullPath: '/admin/courses/$courseId/edit'
      preLoaderRoute: typeof AdminCoursesCourseIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_consumer/products/$productId/purchase': {
      id: '/_consumer/products/$productId/purchase'
      path: '/purchase'
      fullPath: '/products/$productId/purchase'
      preLoaderRoute: typeof ConsumerProductsProductIdPurchaseRouteImport
      parentRoute: typeof ConsumerProductsProductIdRoute
    }
    '/_consumer/_authed/purchases/$purchaseId': {
      id: '/_consumer/_authed/purchases/$purchaseId'
      path: '/purchases/$purchaseId'
      fullPath: '/purchases/$purchaseId'
      preLoaderRoute: typeof ConsumerAuthedPurchasesPurchaseIdRouteImport
      parentRoute: typeof ConsumerAuthedRoute
    }
    '/_consumer/_authed/courses/$courseId/_sidebar': {
      id: '/_consumer/_authed/courses/$courseId/_sidebar'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof ConsumerAuthedCoursesCourseIdSidebarRouteImport
      parentRoute: typeof ConsumerAuthedRoute
    }
    '/_consumer/_authed/courses/$courseId/_sidebar/': {
      id: '/_consumer/_authed/courses/$courseId/_sidebar/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof ConsumerAuthedCoursesCourseIdSidebarIndexRouteImport
      parentRoute: typeof ConsumerAuthedCoursesCourseIdSidebarRoute
    }
  }
}

interface ConsumerAuthedCoursesCourseIdSidebarRouteChildren {
  ConsumerAuthedCoursesCourseIdSidebarIndexRoute: typeof ConsumerAuthedCoursesCourseIdSidebarIndexRoute
}

const ConsumerAuthedCoursesCourseIdSidebarRouteChildren: ConsumerAuthedCoursesCourseIdSidebarRouteChildren =
  {
    ConsumerAuthedCoursesCourseIdSidebarIndexRoute:
      ConsumerAuthedCoursesCourseIdSidebarIndexRoute,
  }

const ConsumerAuthedCoursesCourseIdSidebarRouteWithChildren =
  ConsumerAuthedCoursesCourseIdSidebarRoute._addFileChildren(
    ConsumerAuthedCoursesCourseIdSidebarRouteChildren,
  )

interface ConsumerAuthedRouteChildren {
  ConsumerAuthedPurchasesPurchaseIdRoute: typeof ConsumerAuthedPurchasesPurchaseIdRoute
  ConsumerAuthedCoursesIndexRoute: typeof ConsumerAuthedCoursesIndexRoute
  ConsumerAuthedPurchasesIndexRoute: typeof ConsumerAuthedPurchasesIndexRoute
  ConsumerAuthedCoursesCourseIdSidebarRoute: typeof ConsumerAuthedCoursesCourseIdSidebarRouteWithChildren
}

const ConsumerAuthedRouteChildren: ConsumerAuthedRouteChildren = {
  ConsumerAuthedPurchasesPurchaseIdRoute:
    ConsumerAuthedPurchasesPurchaseIdRoute,
  ConsumerAuthedCoursesIndexRoute: ConsumerAuthedCoursesIndexRoute,
  ConsumerAuthedPurchasesIndexRoute: ConsumerAuthedPurchasesIndexRoute,
  ConsumerAuthedCoursesCourseIdSidebarRoute:
    ConsumerAuthedCoursesCourseIdSidebarRouteWithChildren,
}

const ConsumerAuthedRouteWithChildren = ConsumerAuthedRoute._addFileChildren(
  ConsumerAuthedRouteChildren,
)

interface ConsumerProductsProductIdRouteChildren {
  ConsumerProductsProductIdPurchaseRoute: typeof ConsumerProductsProductIdPurchaseRoute
}

const ConsumerProductsProductIdRouteChildren: ConsumerProductsProductIdRouteChildren =
  {
    ConsumerProductsProductIdPurchaseRoute:
      ConsumerProductsProductIdPurchaseRoute,
  }

const ConsumerProductsProductIdRouteWithChildren =
  ConsumerProductsProductIdRoute._addFileChildren(
    ConsumerProductsProductIdRouteChildren,
  )

interface ConsumerRouteChildren {
  ConsumerAuthedRoute: typeof ConsumerAuthedRouteWithChildren
  ConsumerIndexRoute: typeof ConsumerIndexRoute
  ConsumerProductsProductIdRoute: typeof ConsumerProductsProductIdRouteWithChildren
  ConsumerPurchaseAfterRoute: typeof ConsumerPurchaseAfterRoute
}

const ConsumerRouteChildren: ConsumerRouteChildren = {
  ConsumerAuthedRoute: ConsumerAuthedRouteWithChildren,
  ConsumerIndexRoute: ConsumerIndexRoute,
  ConsumerProductsProductIdRoute: ConsumerProductsProductIdRouteWithChildren,
  ConsumerPurchaseAfterRoute: ConsumerPurchaseAfterRoute,
}

const ConsumerRouteWithChildren = ConsumerRoute._addFileChildren(
  ConsumerRouteChildren,
)

interface AdminRouteChildren {
  AdminSalesRoute: typeof AdminSalesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminCoursesCourseIdEditRoute: typeof AdminCoursesCourseIdEditRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSalesRoute: AdminSalesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminCoursesCourseIdEditRoute: AdminCoursesCourseIdEditRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsumerRoute: ConsumerRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
  ApiWebhooksPaymentRoute: ApiWebhooksPaymentRoute,
  ApiPurchasesPaymentIdInvoiceRoute: ApiPurchasesPaymentIdInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
