/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConsumerRouteImport } from './routes/_consumer'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ConsumerIndexRouteImport } from './routes/_consumer/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminCoursesNewRouteImport } from './routes/admin/courses/new'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products/$productId.edit'
import { Route as AdminCoursesCourseIdEditRouteImport } from './routes/admin/courses/$courseId.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/_consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ConsumerIndexRoute = ConsumerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsumerRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCoursesCourseIdEditRoute =
  AdminCoursesCourseIdEditRouteImport.update({
    id: '/courses/$courseId/edit',
    path: '/courses/$courseId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsumerIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/sales': typeof AdminSalesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/admin/sales': typeof AdminSalesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/': typeof ConsumerIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_consumer': typeof ConsumerRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/sales': typeof AdminSalesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_consumer/': typeof ConsumerIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/sales'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/admin/courses/new'
    | '/admin/products/new'
    | '/api/webhooks/clerk'
    | '/admin/courses/'
    | '/admin/products/'
    | '/admin/courses/$courseId/edit'
    | '/admin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/sales'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/'
    | '/admin'
    | '/admin/courses/new'
    | '/admin/products/new'
    | '/api/webhooks/clerk'
    | '/admin/courses'
    | '/admin/products'
    | '/admin/courses/$courseId/edit'
    | '/admin/products/$productId/edit'
  id:
    | '__root__'
    | '/_consumer'
    | '/admin'
    | '/admin/sales'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_consumer/'
    | '/admin/'
    | '/admin/courses/new'
    | '/admin/products/new'
    | '/api/webhooks/clerk'
    | '/admin/courses/'
    | '/admin/products/'
    | '/admin/courses/$courseId/edit'
    | '/admin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsumerRoute: typeof ConsumerRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_consumer': {
      id: '/_consumer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_consumer/': {
      id: '/_consumer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsumerIndexRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId/edit': {
      id: '/admin/courses/$courseId/edit'
      path: '/courses/$courseId/edit'
      fullPath: '/admin/courses/$courseId/edit'
      preLoaderRoute: typeof AdminCoursesCourseIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface ConsumerRouteChildren {
  ConsumerIndexRoute: typeof ConsumerIndexRoute
}

const ConsumerRouteChildren: ConsumerRouteChildren = {
  ConsumerIndexRoute: ConsumerIndexRoute,
}

const ConsumerRouteWithChildren = ConsumerRoute._addFileChildren(
  ConsumerRouteChildren,
)

interface AdminRouteChildren {
  AdminSalesRoute: typeof AdminSalesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminCoursesCourseIdEditRoute: typeof AdminCoursesCourseIdEditRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSalesRoute: AdminSalesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminCoursesCourseIdEditRoute: AdminCoursesCourseIdEditRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsumerRoute: ConsumerRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
